name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets['EC2_Tiffinpin_devs'] }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      - name: Install dependencies and restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app
          npm install
          pm2 restart all
          EOF